// Generated by gencpp from file agv_msgs/accelerator.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_ACCELERATOR_H
#define AGV_MSGS_MESSAGE_ACCELERATOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_msgs
{
template <class ContainerAllocator>
struct accelerator_
{
  typedef accelerator_<ContainerAllocator> Type;

  accelerator_()
    : accelerator(0)  {
    }
  accelerator_(const ContainerAllocator& _alloc)
    : accelerator(0)  {
  (void)_alloc;
    }



   typedef uint32_t _accelerator_type;
  _accelerator_type accelerator;





  typedef boost::shared_ptr< ::agv_msgs::accelerator_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::accelerator_<ContainerAllocator> const> ConstPtr;

}; // struct accelerator_

typedef ::agv_msgs::accelerator_<std::allocator<void> > accelerator;

typedef boost::shared_ptr< ::agv_msgs::accelerator > acceleratorPtr;
typedef boost::shared_ptr< ::agv_msgs::accelerator const> acceleratorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::accelerator_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::accelerator_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::accelerator_<ContainerAllocator1> & lhs, const ::agv_msgs::accelerator_<ContainerAllocator2> & rhs)
{
  return lhs.accelerator == rhs.accelerator;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::accelerator_<ContainerAllocator1> & lhs, const ::agv_msgs::accelerator_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::accelerator_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::accelerator_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::accelerator_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::accelerator_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::accelerator_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::accelerator_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::accelerator_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d267542ebde270d3d9efa2af5f119108";
  }

  static const char* value(const ::agv_msgs::accelerator_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd267542ebde270d3ULL;
  static const uint64_t static_value2 = 0xd9efa2af5f119108ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::accelerator_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/accelerator";
  }

  static const char* value(const ::agv_msgs::accelerator_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::accelerator_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 accelerator # 油门数据\n"
;
  }

  static const char* value(const ::agv_msgs::accelerator_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::accelerator_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.accelerator);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct accelerator_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::accelerator_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::accelerator_<ContainerAllocator>& v)
  {
    s << indent << "accelerator: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.accelerator);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_ACCELERATOR_H
