// Generated by gencpp from file agv_msgs/actionlimit.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_ACTIONLIMIT_H
#define AGV_MSGS_MESSAGE_ACTIONLIMIT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_msgs
{
template <class ContainerAllocator>
struct actionlimit_
{
  typedef actionlimit_<ContainerAllocator> Type;

  actionlimit_()
    : armlimit(0)
    , fightlimit(0)  {
    }
  actionlimit_(const ContainerAllocator& _alloc)
    : armlimit(0)
    , fightlimit(0)  {
  (void)_alloc;
    }



   typedef uint8_t _armlimit_type;
  _armlimit_type armlimit;

   typedef uint8_t _fightlimit_type;
  _fightlimit_type fightlimit;





  typedef boost::shared_ptr< ::agv_msgs::actionlimit_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::actionlimit_<ContainerAllocator> const> ConstPtr;

}; // struct actionlimit_

typedef ::agv_msgs::actionlimit_<std::allocator<void> > actionlimit;

typedef boost::shared_ptr< ::agv_msgs::actionlimit > actionlimitPtr;
typedef boost::shared_ptr< ::agv_msgs::actionlimit const> actionlimitConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::actionlimit_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::actionlimit_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::actionlimit_<ContainerAllocator1> & lhs, const ::agv_msgs::actionlimit_<ContainerAllocator2> & rhs)
{
  return lhs.armlimit == rhs.armlimit &&
    lhs.fightlimit == rhs.fightlimit;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::actionlimit_<ContainerAllocator1> & lhs, const ::agv_msgs::actionlimit_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::actionlimit_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::actionlimit_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::actionlimit_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::actionlimit_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::actionlimit_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::actionlimit_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::actionlimit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6ed2d9fe059b091ce8972987df0bc2d";
  }

  static const char* value(const ::agv_msgs::actionlimit_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6ed2d9fe059b091ULL;
  static const uint64_t static_value2 = 0xce8972987df0bc2dULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::actionlimit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/actionlimit";
  }

  static const char* value(const ::agv_msgs::actionlimit_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::actionlimit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 armlimit # 大臂和限位1 2\n"
"uint8 fightlimit  # 推斗和限位3 4\n"
;
  }

  static const char* value(const ::agv_msgs::actionlimit_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::actionlimit_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.armlimit);
      stream.next(m.fightlimit);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct actionlimit_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::actionlimit_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::actionlimit_<ContainerAllocator>& v)
  {
    s << indent << "armlimit: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.armlimit);
    s << indent << "fightlimit: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fightlimit);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_ACTIONLIMIT_H
