// Generated by gencpp from file agv_msgs/ArmRequest.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_ARMREQUEST_H
#define AGV_MSGS_MESSAGE_ARMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_msgs
{
template <class ContainerAllocator>
struct ArmRequest_
{
  typedef ArmRequest_<ContainerAllocator> Type;

  ArmRequest_()
    : arm(0)  {
    }
  ArmRequest_(const ContainerAllocator& _alloc)
    : arm(0)  {
  (void)_alloc;
    }



   typedef uint8_t _arm_type;
  _arm_type arm;





  typedef boost::shared_ptr< ::agv_msgs::ArmRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::ArmRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ArmRequest_

typedef ::agv_msgs::ArmRequest_<std::allocator<void> > ArmRequest;

typedef boost::shared_ptr< ::agv_msgs::ArmRequest > ArmRequestPtr;
typedef boost::shared_ptr< ::agv_msgs::ArmRequest const> ArmRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::ArmRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::ArmRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::ArmRequest_<ContainerAllocator1> & lhs, const ::agv_msgs::ArmRequest_<ContainerAllocator2> & rhs)
{
  return lhs.arm == rhs.arm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::ArmRequest_<ContainerAllocator1> & lhs, const ::agv_msgs::ArmRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::ArmRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::ArmRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::ArmRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::ArmRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::ArmRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::ArmRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::ArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e21c483c8d5b2db4fad7ea96e4e9cd5f";
  }

  static const char* value(const ::agv_msgs::ArmRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe21c483c8d5b2db4ULL;
  static const uint64_t static_value2 = 0xfad7ea96e4e9cd5fULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::ArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/ArmRequest";
  }

  static const char* value(const ::agv_msgs::ArmRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::ArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request 第0位:上升 第1位:下降 暂停:00\n"
"uint8 arm\n"
;
  }

  static const char* value(const ::agv_msgs::ArmRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::ArmRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::ArmRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::ArmRequest_<ContainerAllocator>& v)
  {
    s << indent << "arm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.arm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_ARMREQUEST_H
