// Generated by gencpp from file agv_msgs/Brake.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_BRAKE_H
#define AGV_MSGS_MESSAGE_BRAKE_H

#include <ros/service_traits.h>


#include <agv_msgs/BrakeRequest.h>
#include <agv_msgs/BrakeResponse.h>


namespace agv_msgs
{

struct Brake
{

typedef BrakeRequest Request;
typedef BrakeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Brake
} // namespace agv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agv_msgs::Brake > {
  static const char* value()
  {
    return "5b2ec44871413f31c81df6689e271df1";
  }

  static const char* value(const ::agv_msgs::Brake&) { return value(); }
};

template<>
struct DataType< ::agv_msgs::Brake > {
  static const char* value()
  {
    return "agv_msgs/Brake";
  }

  static const char* value(const ::agv_msgs::Brake&) { return value(); }
};


// service_traits::MD5Sum< ::agv_msgs::BrakeRequest> should match
// service_traits::MD5Sum< ::agv_msgs::Brake >
template<>
struct MD5Sum< ::agv_msgs::BrakeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agv_msgs::Brake >::value();
  }
  static const char* value(const ::agv_msgs::BrakeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_msgs::BrakeRequest> should match
// service_traits::DataType< ::agv_msgs::Brake >
template<>
struct DataType< ::agv_msgs::BrakeRequest>
{
  static const char* value()
  {
    return DataType< ::agv_msgs::Brake >::value();
  }
  static const char* value(const ::agv_msgs::BrakeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agv_msgs::BrakeResponse> should match
// service_traits::MD5Sum< ::agv_msgs::Brake >
template<>
struct MD5Sum< ::agv_msgs::BrakeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agv_msgs::Brake >::value();
  }
  static const char* value(const ::agv_msgs::BrakeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_msgs::BrakeResponse> should match
// service_traits::DataType< ::agv_msgs::Brake >
template<>
struct DataType< ::agv_msgs::BrakeResponse>
{
  static const char* value()
  {
    return DataType< ::agv_msgs::Brake >::value();
  }
  static const char* value(const ::agv_msgs::BrakeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGV_MSGS_MESSAGE_BRAKE_H
