// Generated by gencpp from file agv_msgs/Dmode.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_DMODE_H
#define AGV_MSGS_MESSAGE_DMODE_H

#include <ros/service_traits.h>


#include <agv_msgs/DmodeRequest.h>
#include <agv_msgs/DmodeResponse.h>


namespace agv_msgs
{

struct Dmode
{

typedef DmodeRequest Request;
typedef DmodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Dmode
} // namespace agv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agv_msgs::Dmode > {
  static const char* value()
  {
    return "6252fca798177ba9926f15b28891aedb";
  }

  static const char* value(const ::agv_msgs::Dmode&) { return value(); }
};

template<>
struct DataType< ::agv_msgs::Dmode > {
  static const char* value()
  {
    return "agv_msgs/Dmode";
  }

  static const char* value(const ::agv_msgs::Dmode&) { return value(); }
};


// service_traits::MD5Sum< ::agv_msgs::DmodeRequest> should match
// service_traits::MD5Sum< ::agv_msgs::Dmode >
template<>
struct MD5Sum< ::agv_msgs::DmodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agv_msgs::Dmode >::value();
  }
  static const char* value(const ::agv_msgs::DmodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_msgs::DmodeRequest> should match
// service_traits::DataType< ::agv_msgs::Dmode >
template<>
struct DataType< ::agv_msgs::DmodeRequest>
{
  static const char* value()
  {
    return DataType< ::agv_msgs::Dmode >::value();
  }
  static const char* value(const ::agv_msgs::DmodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agv_msgs::DmodeResponse> should match
// service_traits::MD5Sum< ::agv_msgs::Dmode >
template<>
struct MD5Sum< ::agv_msgs::DmodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agv_msgs::Dmode >::value();
  }
  static const char* value(const ::agv_msgs::DmodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_msgs::DmodeResponse> should match
// service_traits::DataType< ::agv_msgs::Dmode >
template<>
struct DataType< ::agv_msgs::DmodeResponse>
{
  static const char* value()
  {
    return DataType< ::agv_msgs::Dmode >::value();
  }
  static const char* value(const ::agv_msgs::DmodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGV_MSGS_MESSAGE_DMODE_H
