// Generated by gencpp from file agv_msgs/DmodeRequest.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_DMODEREQUEST_H
#define AGV_MSGS_MESSAGE_DMODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_msgs
{
template <class ContainerAllocator>
struct DmodeRequest_
{
  typedef DmodeRequest_<ContainerAllocator> Type;

  DmodeRequest_()
    : mode(false)  {
    }
  DmodeRequest_(const ContainerAllocator& _alloc)
    : mode(false)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::agv_msgs::DmodeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::DmodeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DmodeRequest_

typedef ::agv_msgs::DmodeRequest_<std::allocator<void> > DmodeRequest;

typedef boost::shared_ptr< ::agv_msgs::DmodeRequest > DmodeRequestPtr;
typedef boost::shared_ptr< ::agv_msgs::DmodeRequest const> DmodeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::DmodeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::DmodeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::DmodeRequest_<ContainerAllocator1> & lhs, const ::agv_msgs::DmodeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::DmodeRequest_<ContainerAllocator1> & lhs, const ::agv_msgs::DmodeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::DmodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::DmodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::DmodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::DmodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::DmodeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::DmodeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::DmodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3124ebba8ebedcd8ba82847d482ceb7";
  }

  static const char* value(const ::agv_msgs::DmodeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3124ebba8ebedcdULL;
  static const uint64_t static_value2 = 0x8ba82847d482ceb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::DmodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/DmodeRequest";
  }

  static const char* value(const ::agv_msgs::DmodeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::DmodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request false:现场控制 true:远端控制\n"
"bool mode\n"
;
  }

  static const char* value(const ::agv_msgs::DmodeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::DmodeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DmodeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::DmodeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::DmodeRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_DMODEREQUEST_H
