// Generated by gencpp from file agv_msgs/Fight.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_FIGHT_H
#define AGV_MSGS_MESSAGE_FIGHT_H

#include <ros/service_traits.h>


#include <agv_msgs/FightRequest.h>
#include <agv_msgs/FightResponse.h>


namespace agv_msgs
{

struct Fight
{

typedef FightRequest Request;
typedef FightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Fight
} // namespace agv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agv_msgs::Fight > {
  static const char* value()
  {
    return "09fc0f92efe2d6e4a553d7301c89ea7d";
  }

  static const char* value(const ::agv_msgs::Fight&) { return value(); }
};

template<>
struct DataType< ::agv_msgs::Fight > {
  static const char* value()
  {
    return "agv_msgs/Fight";
  }

  static const char* value(const ::agv_msgs::Fight&) { return value(); }
};


// service_traits::MD5Sum< ::agv_msgs::FightRequest> should match
// service_traits::MD5Sum< ::agv_msgs::Fight >
template<>
struct MD5Sum< ::agv_msgs::FightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agv_msgs::Fight >::value();
  }
  static const char* value(const ::agv_msgs::FightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_msgs::FightRequest> should match
// service_traits::DataType< ::agv_msgs::Fight >
template<>
struct DataType< ::agv_msgs::FightRequest>
{
  static const char* value()
  {
    return DataType< ::agv_msgs::Fight >::value();
  }
  static const char* value(const ::agv_msgs::FightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agv_msgs::FightResponse> should match
// service_traits::MD5Sum< ::agv_msgs::Fight >
template<>
struct MD5Sum< ::agv_msgs::FightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agv_msgs::Fight >::value();
  }
  static const char* value(const ::agv_msgs::FightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_msgs::FightResponse> should match
// service_traits::DataType< ::agv_msgs::Fight >
template<>
struct DataType< ::agv_msgs::FightResponse>
{
  static const char* value()
  {
    return DataType< ::agv_msgs::Fight >::value();
  }
  static const char* value(const ::agv_msgs::FightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGV_MSGS_MESSAGE_FIGHT_H
