// Generated by gencpp from file agv_msgs/Gear.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_GEAR_H
#define AGV_MSGS_MESSAGE_GEAR_H

#include <ros/service_traits.h>


#include <agv_msgs/GearRequest.h>
#include <agv_msgs/GearResponse.h>


namespace agv_msgs
{

struct Gear
{

typedef GearRequest Request;
typedef GearResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Gear
} // namespace agv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agv_msgs::Gear > {
  static const char* value()
  {
    return "5a7aecb244ae18cb4ccc55473751bb35";
  }

  static const char* value(const ::agv_msgs::Gear&) { return value(); }
};

template<>
struct DataType< ::agv_msgs::Gear > {
  static const char* value()
  {
    return "agv_msgs/Gear";
  }

  static const char* value(const ::agv_msgs::Gear&) { return value(); }
};


// service_traits::MD5Sum< ::agv_msgs::GearRequest> should match
// service_traits::MD5Sum< ::agv_msgs::Gear >
template<>
struct MD5Sum< ::agv_msgs::GearRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agv_msgs::Gear >::value();
  }
  static const char* value(const ::agv_msgs::GearRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_msgs::GearRequest> should match
// service_traits::DataType< ::agv_msgs::Gear >
template<>
struct DataType< ::agv_msgs::GearRequest>
{
  static const char* value()
  {
    return DataType< ::agv_msgs::Gear >::value();
  }
  static const char* value(const ::agv_msgs::GearRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agv_msgs::GearResponse> should match
// service_traits::MD5Sum< ::agv_msgs::Gear >
template<>
struct MD5Sum< ::agv_msgs::GearResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agv_msgs::Gear >::value();
  }
  static const char* value(const ::agv_msgs::GearResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_msgs::GearResponse> should match
// service_traits::DataType< ::agv_msgs::Gear >
template<>
struct DataType< ::agv_msgs::GearResponse>
{
  static const char* value()
  {
    return DataType< ::agv_msgs::Gear >::value();
  }
  static const char* value(const ::agv_msgs::GearResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGV_MSGS_MESSAGE_GEAR_H
