// Generated by gencpp from file agv_msgs/GearRequest.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_GEARREQUEST_H
#define AGV_MSGS_MESSAGE_GEARREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_msgs
{
template <class ContainerAllocator>
struct GearRequest_
{
  typedef GearRequest_<ContainerAllocator> Type;

  GearRequest_()
    : gear(0)  {
    }
  GearRequest_(const ContainerAllocator& _alloc)
    : gear(0)  {
  (void)_alloc;
    }



   typedef uint8_t _gear_type;
  _gear_type gear;





  typedef boost::shared_ptr< ::agv_msgs::GearRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::GearRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GearRequest_

typedef ::agv_msgs::GearRequest_<std::allocator<void> > GearRequest;

typedef boost::shared_ptr< ::agv_msgs::GearRequest > GearRequestPtr;
typedef boost::shared_ptr< ::agv_msgs::GearRequest const> GearRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::GearRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::GearRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::GearRequest_<ContainerAllocator1> & lhs, const ::agv_msgs::GearRequest_<ContainerAllocator2> & rhs)
{
  return lhs.gear == rhs.gear;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::GearRequest_<ContainerAllocator1> & lhs, const ::agv_msgs::GearRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::GearRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::GearRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::GearRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::GearRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::GearRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::GearRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::GearRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8bb854d7dfa42e038a119fb419a368ec";
  }

  static const char* value(const ::agv_msgs::GearRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8bb854d7dfa42e03ULL;
  static const uint64_t static_value2 = 0x8a119fb419a368ecULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::GearRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/GearRequest";
  }

  static const char* value(const ::agv_msgs::GearRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::GearRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#requset 第0位:上升 第1位:下降 暂停:00\n"
"uint8 gear \n"
;
  }

  static const char* value(const ::agv_msgs::GearRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::GearRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gear);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GearRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::GearRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::GearRequest_<ContainerAllocator>& v)
  {
    s << indent << "gear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gear);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_GEARREQUEST_H
