// Generated by gencpp from file agv_msgs/gearbrake.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_GEARBRAKE_H
#define AGV_MSGS_MESSAGE_GEARBRAKE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_msgs
{
template <class ContainerAllocator>
struct gearbrake_
{
  typedef gearbrake_<ContainerAllocator> Type;

  gearbrake_()
    : gear(0)
    , brake(0)
    , accelerator(0)  {
    }
  gearbrake_(const ContainerAllocator& _alloc)
    : gear(0)
    , brake(0)
    , accelerator(0)  {
  (void)_alloc;
    }



   typedef uint8_t _gear_type;
  _gear_type gear;

   typedef uint8_t _brake_type;
  _brake_type brake;

   typedef uint32_t _accelerator_type;
  _accelerator_type accelerator;





  typedef boost::shared_ptr< ::agv_msgs::gearbrake_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::gearbrake_<ContainerAllocator> const> ConstPtr;

}; // struct gearbrake_

typedef ::agv_msgs::gearbrake_<std::allocator<void> > gearbrake;

typedef boost::shared_ptr< ::agv_msgs::gearbrake > gearbrakePtr;
typedef boost::shared_ptr< ::agv_msgs::gearbrake const> gearbrakeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::gearbrake_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::gearbrake_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::gearbrake_<ContainerAllocator1> & lhs, const ::agv_msgs::gearbrake_<ContainerAllocator2> & rhs)
{
  return lhs.gear == rhs.gear &&
    lhs.brake == rhs.brake &&
    lhs.accelerator == rhs.accelerator;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::gearbrake_<ContainerAllocator1> & lhs, const ::agv_msgs::gearbrake_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::gearbrake_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::gearbrake_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::gearbrake_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::gearbrake_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::gearbrake_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::gearbrake_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::gearbrake_<ContainerAllocator> >
{
  static const char* value()
  {
    return "010d6ca71c6e537a0de387e33a7506ee";
  }

  static const char* value(const ::agv_msgs::gearbrake_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x010d6ca71c6e537aULL;
  static const uint64_t static_value2 = 0x0de387e33a7506eeULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::gearbrake_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/gearbrake";
  }

  static const char* value(const ::agv_msgs::gearbrake_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::gearbrake_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 gear # 档位\n"
"uint8 brake # 刹车\n"
"uint32 accelerator # 油门\n"
;
  }

  static const char* value(const ::agv_msgs::gearbrake_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::gearbrake_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gear);
      stream.next(m.brake);
      stream.next(m.accelerator);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gearbrake_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::gearbrake_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::gearbrake_<ContainerAllocator>& v)
  {
    s << indent << "gear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gear);
    s << indent << "brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brake);
    s << indent << "accelerator: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.accelerator);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_GEARBRAKE_H
