// Generated by gencpp from file agv_msgs/Light.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_LIGHT_H
#define AGV_MSGS_MESSAGE_LIGHT_H

#include <ros/service_traits.h>


#include <agv_msgs/LightRequest.h>
#include <agv_msgs/LightResponse.h>


namespace agv_msgs
{

struct Light
{

typedef LightRequest Request;
typedef LightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Light
} // namespace agv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agv_msgs::Light > {
  static const char* value()
  {
    return "199df97571fbe4ca40cb7e26d6991a7a";
  }

  static const char* value(const ::agv_msgs::Light&) { return value(); }
};

template<>
struct DataType< ::agv_msgs::Light > {
  static const char* value()
  {
    return "agv_msgs/Light";
  }

  static const char* value(const ::agv_msgs::Light&) { return value(); }
};


// service_traits::MD5Sum< ::agv_msgs::LightRequest> should match
// service_traits::MD5Sum< ::agv_msgs::Light >
template<>
struct MD5Sum< ::agv_msgs::LightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agv_msgs::Light >::value();
  }
  static const char* value(const ::agv_msgs::LightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_msgs::LightRequest> should match
// service_traits::DataType< ::agv_msgs::Light >
template<>
struct DataType< ::agv_msgs::LightRequest>
{
  static const char* value()
  {
    return DataType< ::agv_msgs::Light >::value();
  }
  static const char* value(const ::agv_msgs::LightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agv_msgs::LightResponse> should match
// service_traits::MD5Sum< ::agv_msgs::Light >
template<>
struct MD5Sum< ::agv_msgs::LightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agv_msgs::Light >::value();
  }
  static const char* value(const ::agv_msgs::LightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_msgs::LightResponse> should match
// service_traits::DataType< ::agv_msgs::Light >
template<>
struct DataType< ::agv_msgs::LightResponse>
{
  static const char* value()
  {
    return DataType< ::agv_msgs::Light >::value();
  }
  static const char* value(const ::agv_msgs::LightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGV_MSGS_MESSAGE_LIGHT_H
