// Generated by gencpp from file agv_msgs/LightRequest.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_LIGHTREQUEST_H
#define AGV_MSGS_MESSAGE_LIGHTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_msgs
{
template <class ContainerAllocator>
struct LightRequest_
{
  typedef LightRequest_<ContainerAllocator> Type;

  LightRequest_()
    : light(false)  {
    }
  LightRequest_(const ContainerAllocator& _alloc)
    : light(false)  {
  (void)_alloc;
    }



   typedef uint8_t _light_type;
  _light_type light;





  typedef boost::shared_ptr< ::agv_msgs::LightRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::LightRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LightRequest_

typedef ::agv_msgs::LightRequest_<std::allocator<void> > LightRequest;

typedef boost::shared_ptr< ::agv_msgs::LightRequest > LightRequestPtr;
typedef boost::shared_ptr< ::agv_msgs::LightRequest const> LightRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::LightRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::LightRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::LightRequest_<ContainerAllocator1> & lhs, const ::agv_msgs::LightRequest_<ContainerAllocator2> & rhs)
{
  return lhs.light == rhs.light;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::LightRequest_<ContainerAllocator1> & lhs, const ::agv_msgs::LightRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::LightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::LightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::LightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::LightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::LightRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::LightRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::LightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "061309d6ab38f765bedbd876a473855c";
  }

  static const char* value(const ::agv_msgs::LightRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x061309d6ab38f765ULL;
  static const uint64_t static_value2 = 0xbedbd876a473855cULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::LightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/LightRequest";
  }

  static const char* value(const ::agv_msgs::LightRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::LightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request \n"
"bool light\n"
;
  }

  static const char* value(const ::agv_msgs::LightRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::LightRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.light);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LightRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::LightRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::LightRequest_<ContainerAllocator>& v)
  {
    s << indent << "light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.light);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_LIGHTREQUEST_H
